version: '3.7'
      
services:
  selenium_chrome:
    image: selenium/node-chrome:3.141.59-vanadium
    container_name: dockerkvs_selenium_chrome
    depends_on:
      - selenium_hub
    environment:
      - HUB_HOST=selenium_hub
      - HUB_PORT=4444
  selenium_hub:
    image: selenium/hub:3.141.59-vanadium
    container_name: dockerkvs_selenium_hub
    ports:
      - 4444:4444
  webtest:
    build:
      context: ./webtest
      dockerfile: Dockerfile
    image: dockerkvs_webtest  
    container_name: dockerkvs_webtest
    restart: unless-stopped
    depends_on:
      - web
      - selenium_hub
    environment:
      WEB_HOST: web
      WEB_PORT: 80
      SELENIUM_HUB_HOST: selenium_hub
      SELENIUM_HUB_PORT: 4444
    volumes:
      - ./webtest/src:/src
      - ./webtest/images:/images
  apptest:
    build:
      context: ./apptest
      dockerfile: Dockerfile
    image: dockerkvs_apptest
    container_name: dockerkvs_apptest
    restart: unless-stopped
    depends_on:
      - app
    environment:
      APP_HOST: app
      APP_PORT: 80
    volumes:
      - ./apptest/src:/src

  web: 
    build:
      context: ./web
      dockerfile: Dockerfile
    image: dockerkvs_web
    container_name: dockerkvs_web
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - 8080:80
    environment:
      APP_SERVER: http://app:80
    volumes:
      - ./web/html:/usr/share/nginx/html
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: dockerkvs_app
    container_name: dockerkvs_app
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 8081:80
    environment:
      DEBUG: "true"
      REDIS_HOST: db
      REDIS_PORT: 6379
      REDIS_DB: 0
    volumes:
      - ./app/src:/src
  db:
    image: redis:5.0.6-alpine3.10
    restart: unless-stopped
    container_name: dockerkvs_db
    volumes:
      - dockerkvs_redis_volume:/data

volumes:
  dockerkvs_redis_volume:
    driver: local